[_]
schema-version = "0.2"

[[build.buildpacks]]
uri = "paketo-buildpacks/go"

[build]
include = [
  "*.go",
  "go.mod",
  "go.sum"
]

[[build.env]]
name = "BP_GO_TARGETS"
value = "./cmd:gitlab-otel-exporter"
